spring.datasource.url=jdbc:postgresql://localhost:5432/maricelma_massoterapia_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.sercurity.token.secret=${JWT_SECRET: minha-chave-super-segura-123}